#!/usr/bin/env python3
"""MTProxy supervisor: render alexbers configs and reload on shared-volume request."""

from __future__ import annotations

import json
import os
import re
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

CONFIG_PATH = Path(os.environ.get("MTPROXY_CONFIG_PATH", "/var/lib/mtproxy/config.json"))
REQUEST_PATH = Path(
    os.environ.get(
        "MTPROXY_RELOAD_REQUEST_PATH", "/var/lib/overvpn/mtproxy-reload/request"
    )
)
ACK_PATH = Path(
    os.environ.get("MTPROXY_RELOAD_ACK_PATH", "/var/lib/overvpn/mtproxy-reload/ack")
)
PID_PATH = Path(
    os.environ.get("MTPROXY_PID_PATH", "/var/lib/overvpn/mtproxy-reload/mtproxy.pid")
)
WORK_DIR = Path(os.environ.get("MTPROXY_WORK_DIR", "/var/lib/mtproxy-work"))
MTPROXY_SRC = Path(os.environ.get("MTPROXY_SRC", "/opt/mtprotoproxy"))
POLL_SECONDS = float(os.environ.get("MTPROXY_RELOAD_POLL_SECONDS", "0.2"))
SETTLE_SECONDS = float(os.environ.get("MTPROXY_RELOAD_SETTLE_SECONDS", "1"))

SAFE_TAG = re.compile(r"[^A-Za-z0-9._-]+")
children: list[subprocess.Popen[Any]] = []
stopping = False


def log(message: str) -> None:
    print(f"[mtproxy-supervisor] {message}", flush=True)


def write_pid() -> None:
    PID_PATH.parent.mkdir(parents=True, exist_ok=True)
    PID_PATH.write_text(f"{os.getpid()}\n", encoding="utf-8")


def stop_children() -> None:
    global children
    for proc in children:
        if proc.poll() is None:
            proc.terminate()
    deadline = time.time() + 5
    for proc in children:
        remaining = max(0.0, deadline - time.time())
        try:
            proc.wait(timeout=remaining)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=2)
    children = []


def py_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_inbound_config(inbound: dict[str, Any], target: Path) -> None:
    mode = str(inbound.get("secretMode") or "SECURE").upper()
    tls_domain = inbound.get("tlsDomain")
    users = inbound.get("users") or []
    users_lines = []
    for user in users:
        name = str(user.get("name") or "user")
        secret = str(user.get("secret") or "")
        users_lines.append(f"    {py_string(name)}: {py_string(secret)},")
    users_block = "\n".join(users_lines) if users_lines else "    # no users"
    classic = mode == "CLASSIC"
    secure = mode == "SECURE"
    tls = mode == "TLS"
    tls_line = (
        f"TLS_DOMAIN = {py_string(str(tls_domain).strip())}\n"
        if tls and tls_domain
        else ""
    )
    listen_host = str(inbound.get("listenHost") or "0.0.0.0")
    listen_port = int(inbound["listenPort"])
    content = f"""# Generated by OverVPN — do not edit
PORT = {listen_port}
LISTEN_ADDR_IPV4 = {py_string(listen_host)}
LISTEN_ADDR_IPV6 = None
USERS = {{
{users_block}
}}
MODES = {{
    "classic": {str(classic)},
    "secure": {str(secure)},
    "tls": {str(tls)},
}}
{tls_line}"""
    target.write_text(content, encoding="utf-8")


def start_children() -> None:
    global children
    stop_children()
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    raw = CONFIG_PATH.read_text(encoding="utf-8")
    parsed = json.loads(raw)
    inbounds = parsed.get("inbounds") or []
    if not isinstance(inbounds, list):
        raise RuntimeError("config.inbounds must be an array")

    mtproxy_script = MTPROXY_SRC / "mtprotoproxy.py"
    if not mtproxy_script.is_file():
        raise RuntimeError(f"mtprotoproxy.py not found at {mtproxy_script}")

    started: list[subprocess.Popen[Any]] = []
    for index, inbound in enumerate(inbounds):
        if not isinstance(inbound, dict):
            raise RuntimeError("inbound entry must be an object")
        tag = SAFE_TAG.sub("_", str(inbound.get("tag") or f"inbound{index}"))
        conf_path = WORK_DIR / f"{tag}.config.py"
        write_inbound_config(inbound, conf_path)
        log_path = WORK_DIR / f"{tag}.log"
        log_file = open(log_path, "ab", buffering=0)
        proc = subprocess.Popen(
            [sys.executable, str(mtproxy_script), str(conf_path)],
            cwd=str(MTPROXY_SRC),
            stdout=log_file,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        started.append(proc)
        log(f"started {tag} pid={proc.pid} port={inbound.get('listenPort')}")

    time.sleep(SETTLE_SECONDS)
    for proc in started:
        if proc.poll() is not None:
            stop_children_list(started)
            raise RuntimeError(f"mtproxy child exited early with code {proc.returncode}")
    children = started
    if not children:
        log("no MTProxy inbounds configured; supervisor idle")


def stop_children_list(procs: list[subprocess.Popen[Any]]) -> None:
    for proc in procs:
        if proc.poll() is None:
            proc.terminate()
    for proc in procs:
        try:
            proc.wait(timeout=3)
        except subprocess.TimeoutExpired:
            proc.kill()


def write_ack(request_id: str, request_hash: str, status: str, message: str) -> None:
    ACK_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = ACK_PATH.with_suffix(f".tmp.{os.getpid()}")
    tmp.write_text(
        f"id={request_id}\nhash={request_hash}\nstatus={status}\nmessage={message}\n",
        encoding="utf-8",
    )
    tmp.replace(ACK_PATH)


def handle_signal(signum: int, _frame: Any) -> None:
    global stopping
    stopping = True
    log(f"received signal {signum}; shutting down")
    stop_children()
    try:
        PID_PATH.unlink(missing_ok=True)
    except OSError:
        pass
    sys.exit(0)


def parse_request(path: Path) -> tuple[str, str]:
    request_id = ""
    request_hash = ""
    for line in path.read_text(encoding="utf-8").splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key == "id":
            request_id = value
        elif key == "hash":
            request_hash = value
    return request_id, request_hash


def main() -> None:
    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)
    REQUEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    try:
        REQUEST_PATH.unlink(missing_ok=True)
        ACK_PATH.unlink(missing_ok=True)
    except OSError:
        pass

    write_pid()
    start_children()
    last_request_id = ""

    while not stopping:
        for proc in list(children):
            if proc.poll() is not None:
                log(f"child pid={proc.pid} exited with {proc.returncode}")
                stop_children()
                sys.exit(1)

        if REQUEST_PATH.is_file():
            try:
                request_id, request_hash = parse_request(REQUEST_PATH)
            except OSError:
                request_id, request_hash = "", ""
            if request_id and request_id != last_request_id:
                status = "error"
                message = "invalid-request"
                if re.fullmatch(r"[0-9a-f]{64}", request_hash or ""):
                    try:
                        start_children()
                        status = "ok"
                        message = "restarted"
                    except Exception as exc:  # noqa: BLE001
                        message = f"restart-failed:{exc}"
                        try:
                            start_children()
                        except Exception:
                            pass
                else:
                    message = "invalid-hash"
                write_ack(request_id, request_hash, status, message)
                last_request_id = request_id
        time.sleep(POLL_SECONDS)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # noqa: BLE001
        log(f"fatal: {exc}")
        stop_children()
        sys.exit(1)
