#!/usr/bin/env python3
"""MTProxy supervisor: render Telemt configs and reload on shared-volume request."""

from __future__ import annotations

import json
import os
import re
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

CONFIG_PATH = Path(os.environ.get("MTPROXY_CONFIG_PATH", "/var/lib/mtproxy/config.json"))
REQUEST_PATH = Path(
    os.environ.get(
        "MTPROXY_RELOAD_REQUEST_PATH", "/var/lib/overvpn/mtproxy-reload/request"
    )
)
ACK_PATH = Path(
    os.environ.get("MTPROXY_RELOAD_ACK_PATH", "/var/lib/overvpn/mtproxy-reload/ack")
)
PID_PATH = Path(
    os.environ.get("MTPROXY_PID_PATH", "/var/lib/overvpn/mtproxy-reload/mtproxy.pid")
)
WORK_DIR = Path(os.environ.get("MTPROXY_WORK_DIR", "/var/lib/mtproxy-work"))
TELEMT_BIN = Path(os.environ.get("TELEMT_BIN", "/usr/local/bin/telemt"))
POLL_SECONDS = float(os.environ.get("MTPROXY_RELOAD_POLL_SECONDS", "0.2"))
SETTLE_SECONDS = float(os.environ.get("MTPROXY_RELOAD_SETTLE_SECONDS", "1"))
DEFAULT_TLS_DOMAIN = os.environ.get("MTPROXY_DEFAULT_TLS_DOMAIN", "duckduckgo.com")

SAFE_TAG = re.compile(r"[^A-Za-z0-9._-]+")
children: list[subprocess.Popen[Any]] = []
stopping = False


def log(message: str) -> None:
    print(f"[mtproxy-supervisor] {message}", flush=True)


def write_pid() -> None:
    PID_PATH.parent.mkdir(parents=True, exist_ok=True)
    PID_PATH.write_text(f"{os.getpid()}\n", encoding="utf-8")


def stop_children() -> None:
    global children
    for proc in children:
        if proc.poll() is None:
            proc.terminate()
    deadline = time.time() + 5
    for proc in children:
        remaining = max(0.0, deadline - time.time())
        try:
            proc.wait(timeout=remaining)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=2)
    children = []


def toml_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def write_inbound_config(inbound: dict[str, Any], target: Path) -> None:
    mode = str(inbound.get("secretMode") or "SECURE").upper()
    tls_domain_raw = inbound.get("tlsDomain")
    tls_domain = (
        str(tls_domain_raw).strip()
        if tls_domain_raw and str(tls_domain_raw).strip()
        else DEFAULT_TLS_DOMAIN
    )
    users = inbound.get("users") or []
    users_lines: list[str] = []
    for user in users:
        name = str(user.get("name") or "user")
        secret = str(user.get("secret") or "")
        users_lines.append(f"{toml_string(name)} = {toml_string(secret)}")
    users_block = "\n".join(users_lines) if users_lines else "# no users"
    classic = "true" if mode == "CLASSIC" else "false"
    secure = "true" if mode == "SECURE" else "false"
    tls = "true" if mode == "TLS" else "false"
    listen_host = str(inbound.get("listenHost") or "0.0.0.0")
    listen_port = int(inbound["listenPort"])
    content = f"""# Generated by OverVPN — do not edit
[general]
fast_mode = true
use_middle_proxy = false

[general.modes]
classic = {classic}
secure = {secure}
tls = {tls}

[server]
port = {listen_port}
listen_addr_ipv4 = {toml_string(listen_host)}
listen_addr_ipv6 = "::"

[[server.listeners]]
ip = {toml_string(listen_host)}

[timeouts]
client_handshake = 15
tg_connect = 10
client_keepalive = 60
client_ack = 300

[censorship]
tls_domain = {toml_string(tls_domain)}
mask = true

[access.users]
{users_block}
"""
    target.write_text(content, encoding="utf-8")


def start_children() -> None:
    global children
    stop_children()
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    raw = CONFIG_PATH.read_text(encoding="utf-8")
    parsed = json.loads(raw)
    inbounds = parsed.get("inbounds") or []
    if not isinstance(inbounds, list):
        raise RuntimeError("config.inbounds must be an array")

    if not TELEMT_BIN.is_file():
        raise RuntimeError(f"telemt binary not found at {TELEMT_BIN}")
    if not os.access(TELEMT_BIN, os.X_OK):
        raise RuntimeError(f"telemt binary is not executable: {TELEMT_BIN}")

    started: list[subprocess.Popen[Any]] = []
    for index, inbound in enumerate(inbounds):
        if not isinstance(inbound, dict):
            raise RuntimeError("inbound entry must be an object")
        tag = SAFE_TAG.sub("_", str(inbound.get("tag") or f"inbound{index}"))
        conf_path = WORK_DIR / f"{tag}.toml"
        write_inbound_config(inbound, conf_path)
        log_path = WORK_DIR / f"{tag}.log"
        log_file = open(log_path, "ab", buffering=0)
        proc = subprocess.Popen(
            [str(TELEMT_BIN), str(conf_path)],
            cwd=str(WORK_DIR),
            stdout=log_file,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        started.append(proc)
        log(f"started {tag} pid={proc.pid} port={inbound.get('listenPort')}")

    time.sleep(SETTLE_SECONDS)
    for proc in started:
        if proc.poll() is not None:
            stop_children_list(started)
            raise RuntimeError(f"mtproxy child exited early with code {proc.returncode}")
    children = started
    if not children:
        log("no MTProxy inbounds configured; supervisor idle")


def stop_children_list(procs: list[subprocess.Popen[Any]]) -> None:
    for proc in procs:
        if proc.poll() is None:
            proc.terminate()
    for proc in procs:
        try:
            proc.wait(timeout=3)
        except subprocess.TimeoutExpired:
            proc.kill()


def write_ack(request_id: str, request_hash: str, status: str, message: str) -> None:
    ACK_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = ACK_PATH.with_suffix(f".tmp.{os.getpid()}")
    tmp.write_text(
        f"id={request_id}\nhash={request_hash}\nstatus={status}\nmessage={message}\n",
        encoding="utf-8",
    )
    tmp.replace(ACK_PATH)


def handle_signal(signum: int, _frame: Any) -> None:
    global stopping
    stopping = True
    log(f"received signal {signum}; shutting down")
    stop_children()
    try:
        PID_PATH.unlink(missing_ok=True)
    except OSError:
        pass
    sys.exit(0)


def parse_request(path: Path) -> tuple[str, str]:
    request_id = ""
    request_hash = ""
    for line in path.read_text(encoding="utf-8").splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key == "id":
            request_id = value
        elif key == "hash":
            request_hash = value
    return request_id, request_hash


def main() -> None:
    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)
    REQUEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    try:
        REQUEST_PATH.unlink(missing_ok=True)
        ACK_PATH.unlink(missing_ok=True)
    except OSError:
        pass

    write_pid()
    start_children()
    last_request_id = ""

    while not stopping:
        for proc in list(children):
            if proc.poll() is not None:
                log(f"child pid={proc.pid} exited with {proc.returncode}")
                stop_children()
                sys.exit(1)

        if REQUEST_PATH.is_file():
            try:
                request_id, request_hash = parse_request(REQUEST_PATH)
            except OSError:
                request_id, request_hash = "", ""
            if request_id and request_id != last_request_id:
                status = "error"
                message = "invalid-request"
                if re.fullmatch(r"[0-9a-f]{64}", request_hash or ""):
                    try:
                        start_children()
                        status = "ok"
                        message = "restarted"
                    except Exception as exc:  # noqa: BLE001
                        message = f"restart-failed:{exc}"
                        try:
                            start_children()
                        except Exception:
                            pass
                else:
                    message = "invalid-hash"
                write_ack(request_id, request_hash, status, message)
                last_request_id = request_id
        time.sleep(POLL_SECONDS)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # noqa: BLE001
        log(f"fatal: {exc}")
        stop_children()
        sys.exit(1)
